### ISSUE TITLE
The project don't have any C++ files

### ISSUE THREAD

**Issue by osolovyoff** [DarknessFX/DualShock4-For-Unreal-Engine-5#1]
, but how I understand huge part of all hiden inside of BP

**Comment by DarknessFX** [comment]
This project don't need C++, I'm only using native features from UnrealEngine.
The uproject enable RawInput plugin (comes disabled with UE4 and UE5) and have all necessary project settings to make UE5 Enhanced Input work with DualShock4, the BP is just an UserInterface HUD to see each button and axis pressed.
